import type { AppNotification } from "@/lib/types";

export const mockAppNotifications: AppNotification[] = [
  {
    id: "notif_a1",
    type: "success",
    title: "Payment Received",
    titleAr: "تم استلام دفعة",
    message: "SAR 45,000 payment received from Khalid Al-Rashidi for Unit 3B",
    messageAr: "تم استلام دفعة بمبلغ ٤٥,٠٠٠ ر.س من خالد الرشيدي للوحدة 3B",
    link: "/bookings/booking_1",
    read: false,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_a2",
    type: "info",
    title: "New Lead Assigned",
    titleAr: "تم تعيين عميل جديد",
    message: "Mohammed Al-Harbi has been assigned to you. Interested in Villa #12.",
    messageAr: "تم تعيين محمد الحربي لك. مهتم بالفيلا رقم ١٢.",
    link: "/leads",
    read: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_a3",
    type: "warning",
    title: "Milestone Payment Overdue",
    titleAr: "دفعة مرحلة متأخرة",
    message: "2nd installment of SAR 50,000 for Unit 7A is overdue by 3 days",
    messageAr: "القسط الثاني بمبلغ ٥٠,٠٠٠ ر.س للوحدة 7A متأخر بـ ٣ أيام",
    link: "/bookings/booking_2/milestones",
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_a4",
    type: "error",
    title: "Email Delivery Failed",
    titleAr: "فشل إرسال البريد",
    message: "Failed to deliver email to reem@example.com - invalid address",
    messageAr: "فشل إرسال البريد إلى reem@example.com - عنوان غير صالح",
    link: "/communications",
    read: false,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_a5",
    type: "reminder",
    title: "Viewing Appointment Tomorrow",
    titleAr: "موعد معاينة غداً",
    message: "Reminder: Viewing with Sara Al-Otaibi at Al Noor Residence, 10:00 AM",
    messageAr: "تذكير: معاينة مع سارة العتيبي في سكن النور، ١٠:٠٠ صباحاً",
    link: "/leads",
    read: true,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_a6",
    type: "success",
    title: "Booking Confirmed",
    titleAr: "تم تأكيد الحجز",
    message: "Booking BK-2024-003 for Unit 5C has been confirmed",
    messageAr: "تم تأكيد الحجز BK-2024-003 للوحدة 5C",
    link: "/bookings",
    read: true,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_a7",
    type: "info",
    title: "Document Uploaded",
    titleAr: "تم رفع مستند",
    message: "Contract document uploaded for booking BK-2024-001",
    messageAr: "تم رفع مستند عقد للحجز BK-2024-001",
    link: "/documents",
    read: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif_a8",
    type: "warning",
    title: "Campaign Ending Soon",
    titleAr: "الحملة تنتهي قريباً",
    message: "Summer Sale campaign ends in 2 days. 3 units still available.",
    messageAr: "حملة التخفيضات الصيفية تنتهي خلال يومين. ٣ وحدات لا تزال متاحة.",
    link: "/campaigns",
    read: true,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
];
