import type { Communication, EmailTemplate, CommunicationStatus, CommunicationType, CommunicationDirection, TemplateCategory } from "@/lib/types";

export const mockCommunications: Communication[] = [
  {
    id: "comm_1",
    type: "email",
    direction: "outbound",
    contact: { name: "Mohammed Al-Harbi", nameAr: "محمد الحربي", email: "mohammed@example.com" },
    subject: "Property Viewing Confirmation",
    subjectAr: "تأكيد معاينة العقار",
    body: "Dear Mohammed,\n\nWe are pleased to confirm your viewing appointment for Villa #12 at Al Noor Residence on March 15, 2026 at 10:00 AM.\n\nPlease bring a valid ID for entry.\n\nBest regards,\nAhmed Al-Qahtani",
    bodyAr: "عزيزي محمد،\n\nيسعدنا تأكيد موعد معاينتك للفيلا رقم ١٢ في سكن النور يوم ١٥ مارس ٢٠٢٦ الساعة ١٠:٠٠ صباحاً.\n\nيرجى إحضار هوية سارية للدخول.\n\nمع أطيب التحيات،\nأحمد القحطاني",
    status: "delivered",
    leadId: "lead_1",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm_2",
    type: "call",
    direction: "inbound",
    contact: { name: "Khalid Al-Rashidi", nameAr: "خالد الرشيدي", phone: "+966501234567" },
    subject: "Inquiry about 2BR apartments",
    subjectAr: "استفسار عن شقق غرفتين",
    body: "Khalid called asking about available 2-bedroom apartments in Riyadh Tower. Interested in units on higher floors with city view. Budget: 800K-1.2M SAR.",
    status: "sent",
    leadId: "lead_2",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm_3",
    type: "whatsapp",
    direction: "outbound",
    contact: { name: "Sara Al-Otaibi", nameAr: "سارة العتيبي", phone: "+966559876543" },
    subject: "Payment reminder",
    subjectAr: "تذكير بالدفعة",
    body: "Hi Sara, this is a friendly reminder that your next installment of SAR 25,000 is due on March 20th. Please let us know if you have any questions.",
    status: "read",
    bookingId: "booking_1",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm_4",
    type: "sms",
    direction: "outbound",
    contact: { name: "Abdullah Al-Dosari", nameAr: "عبدالله الدوسري", phone: "+966512345678" },
    subject: "Booking confirmed",
    subjectAr: "تم تأكيد الحجز",
    body: "Your booking for Unit 3B at Al Noor Residence has been confirmed. Reference: BK-2024-001",
    status: "delivered",
    bookingId: "booking_2",
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm_5",
    type: "note",
    direction: "outbound",
    contact: { name: "Fahad Al-Shammari", nameAr: "فهد الشمري" },
    subject: "Follow-up note",
    subjectAr: "ملاحظة متابعة",
    body: "Fahad mentioned he needs to discuss with his wife before making a decision. Follow up in 3 days. He prefers WhatsApp communication.",
    status: "sent",
    leadId: "lead_3",
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm_6",
    type: "email",
    direction: "inbound",
    contact: { name: "Nora Al-Qahtani", nameAr: "نورة القحطاني", email: "nora@example.com" },
    subject: "RE: Contract documents",
    subjectAr: "رد: مستندات العقد",
    body: "Hi,\n\nPlease find attached the signed contract documents. I have reviewed everything and all looks good.\n\nRegards,\nNora",
    status: "read",
    bookingId: "booking_3",
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm_7",
    type: "call",
    direction: "outbound",
    contact: { name: "Turki Al-Mutairi", nameAr: "تركي المطيري", phone: "+966507654321" },
    subject: "Price negotiation follow-up",
    subjectAr: "متابعة التفاوض على السعر",
    body: "Called Turki to discuss the counter-offer. He's willing to go up to 950K SAR for the 3BR unit. Need manager approval for discount.",
    status: "sent",
    leadId: "lead_4",
    createdAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm_8",
    type: "email",
    direction: "outbound",
    contact: { name: "Reem Al-Zahrani", nameAr: "ريم الزهراني", email: "reem@example.com" },
    subject: "Welcome to Al Noor Properties",
    subjectAr: "مرحباً بك في عقارات النور",
    body: "Dear Reem,\n\nThank you for your interest in our properties. We have several options that match your requirements.\n\nPlease find attached our latest property brochure.\n\nBest regards",
    status: "failed",
    leadId: "lead_5",
    createdAt: new Date(Date.now() - 150 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 150 * 60 * 60 * 1000).toISOString(),
  },
];

export const COMMUNICATION_STATUS_CONFIG: Record<CommunicationStatus, { color: string; bgClass: string; emoji: string }> = {
  sent: { color: "text-blue-700 dark:text-blue-400", bgClass: "bg-blue-50 dark:bg-blue-950/30", emoji: "📤" },
  delivered: { color: "text-emerald-700 dark:text-emerald-400", bgClass: "bg-emerald-50 dark:bg-emerald-950/30", emoji: "✅" },
  read: { color: "text-green-700 dark:text-green-400", bgClass: "bg-green-50 dark:bg-green-950/30", emoji: "👁" },
  failed: { color: "text-red-700 dark:text-red-400", bgClass: "bg-red-50 dark:bg-red-950/30", emoji: "❌" },
  draft: { color: "text-gray-600 dark:text-gray-400", bgClass: "bg-gray-50 dark:bg-gray-900/30", emoji: "📝" },
  pending: { color: "text-amber-700 dark:text-amber-400", bgClass: "bg-amber-50 dark:bg-amber-950/30", emoji: "⏳" },
};

export const COMMUNICATION_TYPE_CONFIG: Record<CommunicationType, { emoji: string; label: string; labelAr: string }> = {
  email: { emoji: "📧", label: "Email", labelAr: "بريد إلكتروني" },
  sms: { emoji: "💬", label: "SMS", labelAr: "رسالة نصية" },
  whatsapp: { emoji: "📱", label: "WhatsApp", labelAr: "واتساب" },
  call: { emoji: "📞", label: "Call", labelAr: "مكالمة" },
  note: { emoji: "📝", label: "Note", labelAr: "ملاحظة" },
};

export const DIRECTION_CONFIG: Record<CommunicationDirection, { emoji: string; label: string; labelAr: string }> = {
  inbound: { emoji: "↓", label: "Inbound", labelAr: "وارد" },
  outbound: { emoji: "↑", label: "Outbound", labelAr: "صادر" },
};

// Email Templates
export const mockEmailTemplates: EmailTemplate[] = [
  {
    id: "tmpl_1",
    name: "Welcome Email",
    nameAr: "رسالة ترحيب",
    category: "welcome",
    subject: "Welcome to {{propertyName}}!",
    subjectAr: "مرحباً بك في {{propertyName}}!",
    body: "Dear {{leadName}},\n\nThank you for your interest in {{propertyName}}. We are excited to help you find your perfect home.\n\nOur team will be in touch shortly to schedule a viewing.\n\nBest regards,\n{{agentName}}",
    bodyAr: "عزيزي {{leadName}}،\n\nشكراً لاهتمامك بـ {{propertyName}}. نحن متحمسون لمساعدتك في إيجاد منزلك المثالي.\n\nسيتواصل فريقنا معك قريباً لتحديد موعد معاينة.\n\nمع أطيب التحيات،\n{{agentName}}",
    variables: ["leadName", "propertyName", "agentName"],
    isActive: true,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-02-20T14:30:00Z",
  },
  {
    id: "tmpl_2",
    name: "Payment Reminder",
    nameAr: "تذكير بالدفعة",
    category: "payment",
    subject: "Payment Due: {{amount}} for {{unitNumber}}",
    subjectAr: "دفعة مستحقة: {{amount}} لـ {{unitNumber}}",
    body: "Dear {{leadName}},\n\nThis is a friendly reminder that your payment of {{amount}} SAR for {{unitNumber}} at {{propertyName}} is due on {{dueDate}}.\n\nBooking Reference: {{bookingId}}\n\nPlease make the payment at your earliest convenience.\n\nBest regards,\n{{agentName}}",
    bodyAr: "عزيزي {{leadName}}،\n\nهذا تذكير ودي بأن دفعتك بمبلغ {{amount}} ر.س لـ {{unitNumber}} في {{propertyName}} مستحقة في {{dueDate}}.\n\nمرجع الحجز: {{bookingId}}\n\nيرجى إجراء الدفع في أقرب وقت ممكن.\n\nمع أطيب التحيات،\n{{agentName}}",
    variables: ["leadName", "amount", "unitNumber", "propertyName", "dueDate", "bookingId", "agentName"],
    isActive: true,
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-03-01T09:00:00Z",
  },
  {
    id: "tmpl_3",
    name: "Viewing Confirmation",
    nameAr: "تأكيد المعاينة",
    category: "follow_up",
    subject: "Your Viewing at {{propertyName}} is Confirmed",
    subjectAr: "تم تأكيد معاينتك في {{propertyName}}",
    body: "Dear {{leadName}},\n\nYour viewing appointment has been confirmed:\n\nProperty: {{propertyName}}\nUnit: {{unitNumber}}\nDate: {{viewingDate}}\nTime: {{viewingTime}}\n\nPlease bring a valid ID. Our agent {{agentName}} will meet you at the property.\n\nBest regards",
    bodyAr: "عزيزي {{leadName}}،\n\nتم تأكيد موعد معاينتك:\n\nالعقار: {{propertyName}}\nالوحدة: {{unitNumber}}\nالتاريخ: {{viewingDate}}\nالوقت: {{viewingTime}}\n\nيرجى إحضار هوية سارية. سيستقبلك وكيلنا {{agentName}} في العقار.\n\nمع أطيب التحيات",
    variables: ["leadName", "propertyName", "unitNumber", "viewingDate", "viewingTime", "agentName"],
    isActive: true,
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-02-15T11:00:00Z",
  },
  {
    id: "tmpl_4",
    name: "Booking Confirmation",
    nameAr: "تأكيد الحجز",
    category: "booking",
    subject: "Booking Confirmed - {{bookingId}}",
    subjectAr: "تم تأكيد الحجز - {{bookingId}}",
    body: "Dear {{leadName}},\n\nCongratulations! Your booking has been confirmed.\n\nBooking Reference: {{bookingId}}\nUnit: {{unitNumber}}\nProperty: {{propertyName}}\nTotal Amount: {{amount}} SAR\n\nOur team will contact you for the next steps.\n\nBest regards,\n{{agentName}}",
    bodyAr: "عزيزي {{leadName}}،\n\nتهانينا! تم تأكيد حجزك.\n\nمرجع الحجز: {{bookingId}}\nالوحدة: {{unitNumber}}\nالعقار: {{propertyName}}\nالمبلغ الإجمالي: {{amount}} ر.س\n\nسيتواصل فريقنا معك للخطوات التالية.\n\nمع أطيب التحيات،\n{{agentName}}",
    variables: ["leadName", "bookingId", "unitNumber", "propertyName", "amount", "agentName"],
    isActive: true,
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-02-25T14:00:00Z",
  },
  {
    id: "tmpl_5",
    name: "Follow-up After Viewing",
    nameAr: "متابعة بعد المعاينة",
    category: "follow_up",
    subject: "How was your visit to {{propertyName}}?",
    subjectAr: "كيف كانت زيارتك لـ {{propertyName}}؟",
    body: "Dear {{leadName}},\n\nThank you for visiting {{propertyName}} yesterday. We hope you enjoyed the tour.\n\nWe'd love to hear your thoughts. Do you have any questions about the property or would you like to discuss pricing?\n\nFeel free to reach out anytime.\n\nBest regards,\n{{agentName}}",
    bodyAr: "عزيزي {{leadName}}،\n\nشكراً لزيارتك {{propertyName}} أمس. نأمل أنك استمتعت بالجولة.\n\nنود سماع رأيك. هل لديك أي أسئلة حول العقار أو ترغب في مناقشة الأسعار؟\n\nلا تتردد في التواصل معنا في أي وقت.\n\nمع أطيب التحيات،\n{{agentName}}",
    variables: ["leadName", "propertyName", "agentName"],
    isActive: false,
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-03-05T16:00:00Z",
  },
  {
    id: "tmpl_6",
    name: "Campaign Promotion",
    nameAr: "عرض ترويجي",
    category: "marketing",
    subject: "Special Offer: {{discountPercent}}% Off at {{propertyName}}",
    subjectAr: "عرض خاص: خصم {{discountPercent}}% في {{propertyName}}",
    body: "Dear {{leadName}},\n\nExciting news! We're offering a limited-time {{discountPercent}}% discount on selected units at {{propertyName}}.\n\nDon't miss this opportunity to own your dream home at an incredible price.\n\nOffer valid until {{offerEndDate}}.\n\nContact us today!\n\n{{agentName}}",
    bodyAr: "عزيزي {{leadName}}،\n\nأخبار رائعة! نقدم خصماً بنسبة {{discountPercent}}% لفترة محدودة على وحدات مختارة في {{propertyName}}.\n\nلا تفوت هذه الفرصة لامتلاك منزل أحلامك بسعر لا يُصدق.\n\nالعرض ساري حتى {{offerEndDate}}.\n\nتواصل معنا اليوم!\n\n{{agentName}}",
    variables: ["leadName", "propertyName", "discountPercent", "offerEndDate", "agentName"],
    isActive: true,
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
  },
];

export const TEMPLATE_CATEGORY_CONFIG: Record<TemplateCategory, { color: string; bgClass: string; label: string; labelAr: string }> = {
  welcome: { color: "text-blue-700 dark:text-blue-400", bgClass: "bg-blue-50 dark:bg-blue-950/30", label: "Welcome", labelAr: "ترحيب" },
  follow_up: { color: "text-purple-700 dark:text-purple-400", bgClass: "bg-purple-50 dark:bg-purple-950/30", label: "Follow Up", labelAr: "متابعة" },
  payment: { color: "text-emerald-700 dark:text-emerald-400", bgClass: "bg-emerald-50 dark:bg-emerald-950/30", label: "Payment", labelAr: "دفعة" },
  booking: { color: "text-amber-700 dark:text-amber-400", bgClass: "bg-amber-50 dark:bg-amber-950/30", label: "Booking", labelAr: "حجز" },
  general: { color: "text-gray-600 dark:text-gray-400", bgClass: "bg-gray-50 dark:bg-gray-900/30", label: "General", labelAr: "عام" },
  marketing: { color: "text-pink-700 dark:text-pink-400", bgClass: "bg-pink-50 dark:bg-pink-950/30", label: "Marketing", labelAr: "تسويق" },
};
