import type {
  Lead,
  LeadCardData,
  LeadActivity,
  PipelineSummary,
  LeadStage,
} from "./types";

const agents = [
  { id: "agent_1", name: "Saad Al-Harbi", nameAr: "سعد الحربي", avatar: undefined },
  { id: "agent_2", name: "Huda Al-Rashid", nameAr: "هدى الراشد", avatar: undefined },
  { id: "agent_3", name: "Omar Al-Faraj", nameAr: "عمر الفرج", avatar: undefined },
  { id: "agent_4", name: "Noura Al-Saud", nameAr: "نورة السعود", avatar: undefined },
];

export const mockLeads: Lead[] = [
  {
    id: "lead_1",
    contact: { name: "Ahmed Al-Qahtani", nameAr: "أحمد القحطاني", phone: "+966501234567", email: "ahmed@email.com", preferredContact: "whatsapp", preferredLanguage: "ar" },
    score: 85,
    scoreLabel: "hot",
    stage: "new",
    stageChangedAt: "2026-03-10T08:00:00Z",
    interest: { type: "buy", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Riyadh", cityAr: "الرياض", district: "Al Olaya", districtAr: "العليا", budgetMin: 1500000, budgetMax: 2000000, bedrooms: 2, timeline: "1-3months" },
    source: "website",
    agent: agents[0],
    nextAction: { type: "Call", typeAr: "اتصال", date: "2026-03-11T14:00:00Z", description: "Follow-up call", descriptionAr: "مكالمة متابعة" },
    notes: "Looking for family apartment near schools. Prefers higher floors.",
    tags: ["premium", "family"],
    createdAt: "2026-03-08T10:00:00Z",
    updatedAt: "2026-03-10T08:00:00Z",
  },
  {
    id: "lead_2",
    contact: { name: "Fatima Hassan", nameAr: "فاطمة حسن", phone: "+966509876543", email: "fatima@email.com", preferredContact: "email", preferredLanguage: "ar" },
    score: 62,
    scoreLabel: "warm",
    stage: "contacted",
    stageChangedAt: "2026-03-09T12:00:00Z",
    interest: { type: "rent", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Jeddah", cityAr: "جدة", district: "Al Corniche", districtAr: "الكورنيش", budgetMin: 40000, budgetMax: 60000, bedrooms: 3, timeline: "immediate" },
    source: "referral",
    agent: agents[1],
    notes: "Referred by existing tenant. Needs parking.",
    tags: ["referral"],
    createdAt: "2026-03-05T09:00:00Z",
    updatedAt: "2026-03-09T12:00:00Z",
  },
  {
    id: "lead_3",
    contact: { name: "Khalid Ibrahim", nameAr: "خالد إبراهيم", phone: "+966551112233", email: "khalid@corp.com", preferredContact: "phone", preferredLanguage: "en" },
    score: 91,
    scoreLabel: "hot",
    stage: "qualified",
    stageChangedAt: "2026-03-07T15:00:00Z",
    interest: { type: "buy", propertyType: "Villa", propertyTypeAr: "فيلا", city: "Riyadh", cityAr: "الرياض", district: "Al Nakheel", districtAr: "النخيل", budgetMin: 3000000, budgetMax: 4000000, bedrooms: 5, timeline: "1-3months" },
    source: "walk_in",
    agent: agents[0],
    nextAction: { type: "Meeting", typeAr: "اجتماع", date: "2026-03-12T10:00:00Z", description: "Property viewing", descriptionAr: "معاينة العقار" },
    notes: "VIP client. Looking for luxury villa with pool.",
    tags: ["vip", "luxury"],
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-03-07T15:00:00Z",
  },
  {
    id: "lead_4",
    contact: { name: "Sara Ahmed", nameAr: "سارة أحمد", phone: "+966504445566", preferredContact: "whatsapp", preferredLanguage: "ar" },
    score: 55,
    scoreLabel: "warm",
    stage: "viewing",
    stageChangedAt: "2026-03-08T10:00:00Z",
    interest: { type: "rent", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Dammam", cityAr: "الدمام", budgetMin: 30000, budgetMax: 45000, bedrooms: 1, timeline: "immediate" },
    source: "social_media",
    agent: agents[2],
    notes: "Found through Instagram ad. Young professional.",
    tags: ["social"],
    createdAt: "2026-03-03T11:00:00Z",
    updatedAt: "2026-03-08T10:00:00Z",
  },
  {
    id: "lead_5",
    contact: { name: "Omar Nasr", nameAr: "عمر نصر", phone: "+966507778899", email: "omar@business.com", preferredContact: "email", preferredLanguage: "en" },
    score: 88,
    scoreLabel: "hot",
    stage: "negotiation",
    stageChangedAt: "2026-03-06T14:00:00Z",
    interest: { type: "buy", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Riyadh", cityAr: "الرياض", district: "Al Malqa", districtAr: "الملقا", budgetMin: 800000, budgetMax: 1200000, bedrooms: 3, timeline: "1-3months" },
    source: "website",
    agent: agents[0],
    nextAction: { type: "Call", typeAr: "اتصال", date: "2026-03-11T16:00:00Z", description: "Discuss final offer", descriptionAr: "مناقشة العرض النهائي" },
    notes: "Ready to close. Negotiating price.",
    tags: ["closing"],
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-03-06T14:00:00Z",
  },
  {
    id: "lead_6",
    contact: { name: "Abdulaziz Al-Mutairi", nameAr: "عبدالعزيز المطيري", phone: "+966501010101", email: "aziz@mail.com", preferredContact: "phone", preferredLanguage: "ar" },
    score: 78,
    scoreLabel: "warm",
    stage: "new",
    stageChangedAt: "2026-03-10T10:00:00Z",
    interest: { type: "buy", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Riyadh", cityAr: "الرياض", district: "Al Yasmin", districtAr: "الياسمين", budgetMin: 600000, budgetMax: 900000, bedrooms: 2, timeline: "3-6months" },
    source: "phone",
    agent: agents[1],
    notes: "Called in asking about Al Yasmin area.",
    tags: [],
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "lead_7",
    contact: { name: "Mona Al-Zahrani", nameAr: "منى الزهراني", phone: "+966509090909", preferredContact: "whatsapp", preferredLanguage: "ar" },
    score: 35,
    scoreLabel: "cold",
    stage: "contacted",
    stageChangedAt: "2026-03-04T09:00:00Z",
    interest: { type: "rent", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Jeddah", cityAr: "جدة", budgetMin: 25000, budgetMax: 35000, bedrooms: 2, timeline: "6plus" },
    source: "website",
    agent: agents[2],
    notes: "Not in a rush. Exploring options.",
    tags: [],
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-03-04T09:00:00Z",
  },
  {
    id: "lead_8",
    contact: { name: "Turki Al-Dosari", nameAr: "تركي الدوسري", phone: "+966502020202", email: "turki@corp.sa", preferredContact: "email", preferredLanguage: "en" },
    score: 92,
    scoreLabel: "hot",
    stage: "won",
    stageChangedAt: "2026-03-02T16:00:00Z",
    interest: { type: "buy", propertyType: "Penthouse", propertyTypeAr: "بنتهاوس", city: "Riyadh", cityAr: "الرياض", district: "King Abdullah Financial District", districtAr: "حي الملك عبدالله المالي", budgetMin: 5000000, budgetMax: 7000000, bedrooms: 4, timeline: "immediate" },
    source: "partner",
    agent: agents[0],
    notes: "Closed deal! Penthouse in KAFD.",
    tags: ["vip", "closed"],
    createdAt: "2026-01-15T08:00:00Z",
    updatedAt: "2026-03-02T16:00:00Z",
    wonPropertyId: "prop_1",
  },
  {
    id: "lead_9",
    contact: { name: "Reem Al-Otaibi", nameAr: "ريم العتيبي", phone: "+966503030303", preferredContact: "phone", preferredLanguage: "ar" },
    score: 44,
    scoreLabel: "cold",
    stage: "lost",
    stageChangedAt: "2026-03-05T11:00:00Z",
    interest: { type: "rent", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Riyadh", cityAr: "الرياض", budgetMin: 20000, budgetMax: 30000, bedrooms: 1, timeline: "immediate" },
    source: "website",
    agent: agents[3],
    lostReason: "Budget too low for available units.",
    notes: "",
    tags: [],
    createdAt: "2026-02-25T09:00:00Z",
    updatedAt: "2026-03-05T11:00:00Z",
  },
  {
    id: "lead_10",
    contact: { name: "Majid Al-Ghamdi", nameAr: "ماجد الغامدي", phone: "+966504040404", email: "majid@email.com", preferredContact: "whatsapp", preferredLanguage: "ar" },
    score: 72,
    scoreLabel: "warm",
    stage: "qualified",
    stageChangedAt: "2026-03-09T14:00:00Z",
    interest: { type: "buy", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Riyadh", cityAr: "الرياض", district: "Al Sahafa", districtAr: "الصحافة", budgetMin: 700000, budgetMax: 1000000, bedrooms: 3, timeline: "3-6months" },
    source: "referral",
    agent: agents[1],
    nextAction: { type: "Email", typeAr: "بريد", date: "2026-03-12T09:00:00Z", description: "Send property options", descriptionAr: "إرسال خيارات العقارات" },
    notes: "Referred by Turki Al-Dosari.",
    tags: ["referral"],
    createdAt: "2026-03-06T10:00:00Z",
    updatedAt: "2026-03-09T14:00:00Z",
  },
  {
    id: "lead_11",
    contact: { name: "Layla Al-Shahrani", nameAr: "ليلى الشهراني", phone: "+966505050505", preferredContact: "phone", preferredLanguage: "ar" },
    score: 68,
    scoreLabel: "warm",
    stage: "new",
    stageChangedAt: "2026-03-10T15:00:00Z",
    interest: { type: "rent", propertyType: "Villa", propertyTypeAr: "فيلا", city: "Riyadh", cityAr: "الرياض", district: "Hittin", districtAr: "حطين", budgetMin: 80000, budgetMax: 120000, bedrooms: 4, timeline: "1-3months" },
    source: "social_media",
    agent: agents[3],
    notes: "Interested in gated community.",
    tags: ["family"],
    createdAt: "2026-03-10T15:00:00Z",
    updatedAt: "2026-03-10T15:00:00Z",
  },
  {
    id: "lead_12",
    contact: { name: "Fahad Al-Otaibi", nameAr: "فهد العتيبي", phone: "+966506060606", email: "fahad@company.sa", preferredContact: "email", preferredLanguage: "en" },
    score: 81,
    scoreLabel: "hot",
    stage: "viewing",
    stageChangedAt: "2026-03-07T11:00:00Z",
    interest: { type: "buy", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Riyadh", cityAr: "الرياض", district: "Al Narjis", districtAr: "النرجس", budgetMin: 500000, budgetMax: 750000, bedrooms: 2, timeline: "immediate" },
    source: "walk_in",
    agent: agents[0],
    nextAction: { type: "Meeting", typeAr: "اجتماع", date: "2026-03-13T11:00:00Z", description: "Second viewing", descriptionAr: "معاينة ثانية" },
    notes: "Liked unit 301. Wants second viewing.",
    tags: [],
    createdAt: "2026-02-28T09:00:00Z",
    updatedAt: "2026-03-07T11:00:00Z",
  },
  {
    id: "lead_13",
    contact: { name: "Nasser Al-Harbi", nameAr: "ناصر الحربي", phone: "+966507070707", preferredContact: "phone", preferredLanguage: "ar" },
    score: 48,
    scoreLabel: "cold",
    stage: "contacted",
    stageChangedAt: "2026-03-08T08:00:00Z",
    interest: { type: "rent", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Dammam", cityAr: "الدمام", budgetMin: 20000, budgetMax: 30000, bedrooms: 1, timeline: "6plus" },
    source: "phone",
    agent: agents[2],
    notes: "Inquired about prices. Not urgent.",
    tags: [],
    createdAt: "2026-03-06T08:00:00Z",
    updatedAt: "2026-03-08T08:00:00Z",
  },
  {
    id: "lead_14",
    contact: { name: "Salma Al-Qahtani", nameAr: "سلمى القحطاني", phone: "+966508080808", email: "salma@mail.com", preferredContact: "whatsapp", preferredLanguage: "ar" },
    score: 90,
    scoreLabel: "hot",
    stage: "won",
    stageChangedAt: "2026-02-28T14:00:00Z",
    interest: { type: "buy", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Jeddah", cityAr: "جدة", district: "Al Hamra", districtAr: "الحمراء", budgetMin: 1200000, budgetMax: 1600000, bedrooms: 3, timeline: "immediate" },
    source: "website",
    agent: agents[1],
    notes: "Closed successfully.",
    tags: ["closed"],
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-02-28T14:00:00Z",
    wonPropertyId: "prop_2",
  },
  {
    id: "lead_15",
    contact: { name: "Yousef Al-Dosari", nameAr: "يوسف الدوسري", phone: "+966509999999", preferredContact: "phone", preferredLanguage: "ar" },
    score: 30,
    scoreLabel: "cold",
    stage: "lost",
    stageChangedAt: "2026-03-01T09:00:00Z",
    interest: { type: "rent", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Riyadh", cityAr: "الرياض", budgetMin: 15000, budgetMax: 25000, bedrooms: 1, timeline: "immediate" },
    source: "social_media",
    agent: agents[3],
    lostReason: "Found another property.",
    notes: "",
    tags: [],
    createdAt: "2026-02-15T08:00:00Z",
    updatedAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "lead_16",
    contact: { name: "Hanan Al-Shammari", nameAr: "حنان الشمري", phone: "+966501111111", email: "hanan@email.com", preferredContact: "email", preferredLanguage: "en" },
    score: 76,
    scoreLabel: "warm",
    stage: "negotiation",
    stageChangedAt: "2026-03-09T16:00:00Z",
    interest: { type: "buy", propertyType: "Apartment", propertyTypeAr: "شقة", city: "Riyadh", cityAr: "الرياض", district: "Al Aqiq", districtAr: "العقيق", budgetMin: 900000, budgetMax: 1300000, bedrooms: 3, timeline: "1-3months" },
    source: "referral",
    agent: agents[0],
    nextAction: { type: "Call", typeAr: "اتصال", date: "2026-03-11T11:00:00Z", description: "Counter offer discussion", descriptionAr: "مناقشة العرض المقابل" },
    notes: "Negotiating terms. Wants installment plan.",
    tags: ["negotiating"],
    createdAt: "2026-02-10T08:00:00Z",
    updatedAt: "2026-03-09T16:00:00Z",
  },
];

export function leadToCardData(lead: Lead): LeadCardData {
  return {
    id: lead.id,
    name: lead.contact.name,
    nameAr: lead.contact.nameAr,
    score: lead.score,
    scoreLabel: lead.scoreLabel,
    location: lead.interest.district
      ? `${lead.interest.district}, ${lead.interest.city}`
      : lead.interest.city,
    locationAr: lead.interest.districtAr
      ? `${lead.interest.districtAr}، ${lead.interest.cityAr}`
      : lead.interest.cityAr,
    interest: `${lead.interest.bedrooms ? lead.interest.bedrooms + "BR " : ""}${lead.interest.propertyType}`,
    interestAr: `${lead.interest.bedrooms ? lead.interest.bedrooms + " غرف " : ""}${lead.interest.propertyTypeAr}`,
    budgetMin: lead.interest.budgetMin,
    budgetMax: lead.interest.budgetMax,
    agent: lead.agent,
    nextAction: lead.nextAction ? { type: lead.nextAction.type, date: lead.nextAction.date } : undefined,
    lastActivityAt: lead.updatedAt,
    stage: lead.stage,
    source: lead.source,
    phone: lead.contact.phone,
    email: lead.contact.email,
  };
}

export const mockPipelineSummary: PipelineSummary = {
  stages: [
    { stage: "new", count: 3, totalValue: 4300000 },
    { stage: "contacted", count: 3, totalValue: 1600000 },
    { stage: "qualified", count: 2, totalValue: 4500000 },
    { stage: "viewing", count: 2, totalValue: 1550000 },
    { stage: "negotiation", count: 2, totalValue: 3200000 },
    { stage: "won", count: 2, totalValue: 13600000 },
    { stage: "lost", count: 2, totalValue: 400000 },
  ],
  conversionRate: 27,
  avgDaysToClose: 14,
  totalLeads: 16,
  activeLeads: 12,
};

export const mockLeadActivities: LeadActivity[] = [
  { id: "act_1", type: "call", title: "Call scheduled", titleAr: "تم جدولة مكالمة", description: "Follow-up call at 2:00 PM", descriptionAr: "مكالمة متابعة الساعة 2:00 مساءً", actor: { name: "Saad Al-Harbi", nameAr: "سعد الحربي" }, timestamp: "2026-03-11T14:00:00Z" },
  { id: "act_2", type: "email", title: "Brochure sent", titleAr: "تم إرسال الكتيب", description: "Sent property brochure and pricing details", descriptionAr: "تم إرسال كتيب العقار وتفاصيل الأسعار", actor: { name: "Saad Al-Harbi", nameAr: "سعد الحربي" }, timestamp: "2026-03-10T09:00:00Z" },
  { id: "act_3", type: "status_change", title: "Stage changed to New", titleAr: "تم تغيير المرحلة إلى جديد", actor: { name: "System", nameAr: "النظام" }, timestamp: "2026-03-08T10:00:00Z" },
  { id: "act_4", type: "note", title: "Note added", titleAr: "تمت إضافة ملاحظة", description: "Looking for family apartment near schools. Prefers higher floors.", descriptionAr: "يبحث عن شقة عائلية بالقرب من المدارس. يفضل الطوابق العلوية.", actor: { name: "Saad Al-Harbi", nameAr: "سعد الحربي" }, timestamp: "2026-03-08T10:05:00Z" },
  { id: "act_5", type: "system", title: "Lead created", titleAr: "تم إنشاء العميل المحتمل", description: "Source: Website form", descriptionAr: "المصدر: نموذج الموقع", actor: { name: "System", nameAr: "النظام" }, timestamp: "2026-03-08T10:00:00Z" },
];

export const LEAD_STAGES: LeadStage[] = ["new", "contacted", "qualified", "viewing", "negotiation", "won", "lost"];

export const STAGE_COLORS: Record<LeadStage, string> = {
  new: "bg-slate-500",
  contacted: "bg-blue-500",
  qualified: "bg-purple-500",
  viewing: "bg-cyan-500",
  negotiation: "bg-amber-500",
  won: "bg-green-500",
  lost: "bg-red-500",
};

export const STAGE_BG_COLORS: Record<LeadStage, string> = {
  new: "bg-slate-100 dark:bg-slate-900/30",
  contacted: "bg-blue-100 dark:bg-blue-900/30",
  qualified: "bg-purple-100 dark:bg-purple-900/30",
  viewing: "bg-cyan-100 dark:bg-cyan-900/30",
  negotiation: "bg-amber-100 dark:bg-amber-900/30",
  won: "bg-green-100 dark:bg-green-900/30",
  lost: "bg-red-100 dark:bg-red-900/30",
};
