import type { Document, DocumentCategory } from "@/lib/types";

export const mockDocuments: Document[] = [
  {
    id: "doc_1",
    name: "Sales Agreement - Unit 3B",
    nameAr: "عقد بيع - الوحدة 3B",
    category: "contract",
    entityType: "booking",
    entityId: "booking_1",
    entityName: "Booking BK-2024-001",
    entityNameAr: "حجز BK-2024-001",
    description: "Signed sales agreement for Unit 3B at Al Noor Residence",
    descriptionAr: "عقد بيع موقع للوحدة 3B في سكن النور",
    url: "https://storage.example.com/docs/contract-3b.pdf",
    fileSize: 2450000,
    mimeType: "application/pdf",
    tags: ["contract", "signed", "unit-3b"],
    uploadedBy: { id: "user_1", name: "Ahmed Al-Qahtani", nameAr: "أحمد القحطاني" },
    isArchived: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "doc_2",
    name: "Invoice #INV-2024-042",
    nameAr: "فاتورة #INV-2024-042",
    category: "invoice",
    entityType: "booking",
    entityId: "booking_2",
    entityName: "Booking BK-2024-002",
    entityNameAr: "حجز BK-2024-002",
    description: "Down payment invoice for Unit 7A",
    url: "https://storage.example.com/docs/invoice-042.pdf",
    fileSize: 185000,
    mimeType: "application/pdf",
    tags: ["invoice", "down-payment"],
    uploadedBy: { id: "user_1", name: "Ahmed Al-Qahtani", nameAr: "أحمد القحطاني" },
    isArchived: false,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "doc_3",
    name: "Payment Receipt - SAR 45,000",
    nameAr: "إيصال دفع - ٤٥,٠٠٠ ر.س",
    category: "receipt",
    entityType: "booking",
    entityId: "booking_1",
    entityName: "Booking BK-2024-001",
    entityNameAr: "حجز BK-2024-001",
    url: "https://storage.example.com/docs/receipt-001.pdf",
    fileSize: 95000,
    mimeType: "application/pdf",
    tags: ["receipt", "payment"],
    uploadedBy: { id: "user_2", name: "Saad Al-Dosari", nameAr: "سعد الدوسري" },
    isArchived: false,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "doc_4",
    name: "National ID - Mohammed Al-Harbi",
    nameAr: "هوية وطنية - محمد الحربي",
    category: "id",
    entityType: "lead",
    entityId: "lead_1",
    entityName: "Mohammed Al-Harbi",
    entityNameAr: "محمد الحربي",
    url: "https://storage.example.com/docs/id-mohammed.jpg",
    fileSize: 520000,
    mimeType: "image/jpeg",
    tags: ["id", "national-id"],
    uploadedBy: { id: "user_1", name: "Ahmed Al-Qahtani", nameAr: "أحمد القحطاني" },
    isArchived: false,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "doc_5",
    name: "Title Deed - Al Noor Residence",
    nameAr: "صك ملكية - سكن النور",
    category: "deed",
    entityType: "property",
    entityId: "prop_1",
    entityName: "Al Noor Residence",
    entityNameAr: "سكن النور",
    description: "Official title deed for Al Noor Residence compound",
    descriptionAr: "صك الملكية الرسمي لمجمع سكن النور",
    url: "https://storage.example.com/docs/deed-alnoor.pdf",
    fileSize: 4200000,
    mimeType: "application/pdf",
    tags: ["deed", "official", "al-noor"],
    uploadedBy: { id: "user_1", name: "Ahmed Al-Qahtani", nameAr: "أحمد القحطاني" },
    isArchived: false,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "doc_6",
    name: "Floor Plan - Building A, Floor 3",
    nameAr: "مخطط طابق - المبنى أ، الطابق ٣",
    category: "floor_plan",
    entityType: "property",
    entityId: "prop_1",
    entityName: "Al Noor Residence",
    entityNameAr: "سكن النور",
    url: "https://storage.example.com/docs/floorplan-a3.pdf",
    fileSize: 1800000,
    mimeType: "application/pdf",
    tags: ["floor-plan", "building-a"],
    uploadedBy: { id: "user_2", name: "Saad Al-Dosari", nameAr: "سعد الدوسري" },
    isArchived: false,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "doc_7",
    name: "Lease Contract - Unit 7A (archived)",
    nameAr: "عقد إيجار - الوحدة 7A (مؤرشف)",
    category: "contract",
    entityType: "unit",
    entityId: "unit_7a",
    entityName: "Unit 7A",
    entityNameAr: "الوحدة 7A",
    url: "https://storage.example.com/docs/lease-7a-old.pdf",
    fileSize: 1200000,
    mimeType: "application/pdf",
    tags: ["lease", "archived"],
    uploadedBy: { id: "user_1", name: "Ahmed Al-Qahtani", nameAr: "أحمد القحطاني" },
    isArchived: true,
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "doc_8",
    name: "Miscellaneous - Site Photos",
    nameAr: "متنوع - صور الموقع",
    category: "other",
    entityType: "property",
    entityId: "prop_2",
    entityName: "Riyadh Tower",
    entityNameAr: "برج الرياض",
    url: "https://storage.example.com/docs/site-photos.zip",
    fileSize: 15600000,
    mimeType: "application/zip",
    tags: ["photos", "site"],
    uploadedBy: { id: "user_2", name: "Saad Al-Dosari", nameAr: "سعد الدوسري" },
    isArchived: false,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DOCUMENT_CATEGORY_CONFIG: Record<DocumentCategory, { emoji: string; color: string; bgClass: string; label: string; labelAr: string }> = {
  contract: { emoji: "📄", color: "text-blue-700 dark:text-blue-400", bgClass: "bg-blue-50 dark:bg-blue-950/30", label: "Contract", labelAr: "عقد" },
  invoice: { emoji: "🧾", color: "text-emerald-700 dark:text-emerald-400", bgClass: "bg-emerald-50 dark:bg-emerald-950/30", label: "Invoice", labelAr: "فاتورة" },
  receipt: { emoji: "🧾", color: "text-green-700 dark:text-green-400", bgClass: "bg-green-50 dark:bg-green-950/30", label: "Receipt", labelAr: "إيصال" },
  id: { emoji: "🪪", color: "text-purple-700 dark:text-purple-400", bgClass: "bg-purple-50 dark:bg-purple-950/30", label: "ID", labelAr: "هوية" },
  deed: { emoji: "📜", color: "text-amber-700 dark:text-amber-400", bgClass: "bg-amber-50 dark:bg-amber-950/30", label: "Deed", labelAr: "صك" },
  floor_plan: { emoji: "🏗️", color: "text-cyan-700 dark:text-cyan-400", bgClass: "bg-cyan-50 dark:bg-cyan-950/30", label: "Floor Plan", labelAr: "مخطط" },
  other: { emoji: "📁", color: "text-gray-600 dark:text-gray-400", bgClass: "bg-gray-50 dark:bg-gray-900/30", label: "Other", labelAr: "أخرى" },
};
